# Generated by Django 3.1.1 on 2020-09-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='posted_on',
            new_name='posted_date',
        ),
    ]
