# Generated by Django 3.1.1 on 2020-09-18 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0002_auto_20200918_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CatTitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
