# Generated by Django 3.1.1 on 2020-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0003_auto_20200918_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
