# Generated by Django 3.1.1 on 2020-09-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0004_blogpost_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='view',
        ),
    ]
