# Generated by Django 3.1.1 on 2020-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0008_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='manu_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
