# Generated by Django 3.1.1 on 2020-09-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0010_socialwidget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SocialWidget',
        ),
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='author',
            name='author_social_link_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_social_link_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
