# Generated by Django 3.1.1 on 2020-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0011_auto_20200919_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_social_link_name',
            new_name='author_facebook_url',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_social_link_url',
            new_name='author_github_url',
        ),
        migrations.AddField(
            model_name='author',
            name='author_instagram_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_twitter_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
