# Generated by Django 3.1.1 on 2020-09-19 04:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0013_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('post_body', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('posted_date', models.DateField(default=datetime.date.today)),
                ('publish', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogWebsite.author')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SiteLogo',
        ),
    ]
