# Generated by Django 3.1.1 on 2020-09-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0014_auto_20200919_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPages',
        ),
    ]
