# Generated by Django 3.1.1 on 2020-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0018_logo_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
