# Generated by Django 3.1.1 on 2020-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0020_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
