# Generated by Django 3.1.1 on 2020-09-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogWebsite', '0023_footersocial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
